apiVersion: 1

datasources:
  - name: SDOQAP_Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      timeField: timestamp
      esVersion: "8.0.0"
      index: "sdoqap_*"
