FROM node:20-alpine as build
WORKDIR /app
COPY package.json vite.config.js .
ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN npm install
COPY src ./src
COPY index.html .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
